name: flutter_todo_app_with_hasura
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  hasura_connect: ^0.1.3
  datetime_picker_formfield: ^0.4.3
  intl: ^0.15.8
  dropdown_formfield: ^0.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  # assets:
  #  - images/a_dot_burr.jpeg
